version: "3.9"
services:
  backend:
    container_name: backend
    build: ./src  
    ports:
      - "8080:8080"
    networks:
      - todonet
    depends_on:
      - database
  frontend:
    container_name: frontend
    networks:
      - todonet
    ports:
      - "8090:8090"
    expose:
      - "8090"
    environment:
      - SERVER_PORT=8090
      - BACKEND_ENDPOINT=http://backend:8080/
    image: "maeddes/hsefrontend:v231"
  database:
    container_name: postgresdb
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=TodoApp
      - POSTGRES_PASSWORD=MyTodo
      - POSTGRES_DB=todo
    ports:
      - 5432:5432
    networks:
      - todonet
    volumes:
      - todovol:/var/lib/postgresql/data 
networks:
  todonet:
    name: todonet

volumes:
  todovol:
    external: false